import { callAI } from './api';

const DECOMPOSER_SYSTEM_PROMPT = `You are the Decomposer Agent in a multi-agent task planning system.
Your goal is to break down a complex, high-level task/goal into exactly 8 distinct, key sub-themes or categories.
These 8 sub-themes will form the "petals" of a 3x3 Lotus Blossom grid.

Your output must be a valid JSON object containing a single key "subtasks", which is an array of exactly 8 strings.
Do not include any extra text, explanation, or markdown. Only return the raw JSON object.
Each subtask should be concise (2-5 words), actionable, and represent a unique, non-overlapping area of the core task.

Example output:
{
  "subtasks": [
    "Market Research",
    "Product Design",
    "Frontend Development",
    "Backend Infrastructure",
    "Marketing & Launch",
    "Legal & Setup",
    "User Testing",
    "Customer Support"
  ]
}`;

const CRITIC_SYSTEM_PROMPT = `You are the Critic Agent in a multi-agent task planning system.
Your job is to evaluate the 8 sub-themes generated by the Decomposer Agent for a core task.

Analyze them for:
1. Redundancy (are any sub-themes overlapping or repetitive?).
2. Completeness (is there an obvious, critical category missing?).
3. Clarity and actionability (are they vague?).

You must provide a constructive feedback critique, and output a revised, improved list of exactly 8 sub-themes that incorporates your improvements.
Your output must be a valid JSON object with the following fields:
{
  "isApproved": boolean,
  "feedback": "Your detailed evaluation and critique (1-2 sentences)",
  "suggestions": ["Subtask 1", "Subtask 2", ..., "Subtask 8"] (exactly 8 strings, representing your refined list)
}
Do not include any extra text, explanation, or markdown. Only return the raw JSON object.`;

// Helper to clean LLM markdown codeblock wrappings if any
const cleanJSON = (str) => {
  let cleaned = str.trim();
  if (cleaned.startsWith('```json')) {
    cleaned = cleaned.substring(7);
  } else if (cleaned.startsWith('```')) {
    cleaned = cleaned.substring(3);
  }
  if (cleaned.endsWith('```')) {
    cleaned = cleaned.substring(0, cleaned.length - 3);
  }
  return JSON.parse(cleaned.trim());
};

export const decomposeLotusTask = async (coreTask, settings, onLog) => {
  try {
    // Step 1: Decomposer
    onLog({
      agent: 'Decomposer Agent',
      status: 'thinking',
      message: `Analyzing core task: "${coreTask}". Generating 8 primary strategic themes...`
    });

    const decomposerResponseText = await callAI(
      settings,
      DECOMPOSER_SYSTEM_PROMPT,
      `Decompose this core task: "${coreTask}"`,
      true
    );

    let decomposerData;
    try {
      decomposerData = cleanJSON(decomposerResponseText);
      if (!decomposerData.subtasks || !Array.isArray(decomposerData.subtasks) || decomposerData.subtasks.length !== 8) {
        throw new Error('Decomposer did not return exactly 8 subtasks.');
      }
    } catch (e) {
      console.error('Failed to parse Decomposer output:', decomposerResponseText, e);
      throw new Error('Decomposer returned invalid JSON. Try again.');
    }

    onLog({
      agent: 'Decomposer Agent',
      status: 'success',
      message: `Generated initial draft:`,
      data: decomposerData.subtasks
    });

    // Step 2: Critic
    onLog({
      agent: 'Critic Agent',
      status: 'thinking',
      message: `Analyzing the Decomposer's draft for quality, coverage gaps, and redundancies...`
    });

    const criticUserPrompt = `Core Task: "${coreTask}"
Decomposer Draft: ${JSON.stringify(decomposerData.subtasks)}`;

    const criticResponseText = await callAI(
      settings,
      CRITIC_SYSTEM_PROMPT,
      criticUserPrompt,
      true
    );

    let criticData;
    try {
      criticData = cleanJSON(criticResponseText);
      if (!criticData.suggestions || !Array.isArray(criticData.suggestions) || criticData.suggestions.length !== 8) {
        throw new Error('Critic did not suggest exactly 8 subtasks.');
      }
    } catch (e) {
      console.error('Failed to parse Critic output:', criticResponseText, e);
      throw new Error('Critic returned invalid JSON. Try again.');
    }

    onLog({
      agent: 'Critic Agent',
      status: criticData.isApproved ? 'success' : 'warning',
      message: `Critic Review [Approved: ${criticData.isApproved}]: "${criticData.feedback}"`,
      data: criticData.suggestions
    });

    // Step 3: Orchestrator
    onLog({
      agent: 'System Orchestrator',
      status: 'success',
      message: `Decomposition finalized successfully using consensus-refined suggestions.`
    });

    return {
      success: true,
      draft: decomposerData.subtasks,
      feedback: criticData.feedback,
      finalSubtasks: criticData.suggestions
    };
  } catch (error) {
    onLog({
      agent: 'System Orchestrator',
      status: 'error',
      message: `Failed during decomposition: ${error.message}`
    });
    throw error;
  }
};
